#spring.profiles.active=prod
server.port: 8080
spring:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: update
  hateoas.use-hal-as-default-json-media-type: false
  data.rest.defaultMediaType: application/json
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:8080'
#          jws-algorithm: HS256


#management.endpoints.web.exposure.include= health,info,beans
#management.endpoint.health.show-details=always

#spring.banner.image.location=classpath:photo_2020-11-28_23-55-33.jpg
#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect
#spring.jpa.generate-ddl=false
