spring.datasource:
#  url: jdbc:postgresql://localhost:5432/mydb/postgres
  url: jdbc:postgresql://database-1.c1xkrasagvnr.us-east-2.rds.amazonaws.com:5432/
  driver-class-name: org.postgresql.Driver
  username: postgres
  password: 'mypassword'